### ISSUE TITLE
如何直接调用openai的api

### ISSUE THREAD

**Issue by 6chenhua** [linjungz/chatgpt-comment-analyzer#1]
这段代码里调用的是Azure上的openai的api，这样比直接调用麻烦很多，如何直接调用呢

**Comment by linjungz** [comment]
这个直接找下azure openai的官网就有例子了


https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&amp;pivots=programming-language-studio



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenhualiu ***@***.***&gt;
发送时间: 2023年7月4日 21:40
收件人: linjungz/chatgpt-comment-analyzer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [linjungz/chatgpt-comment-analyzer] 如何直接调用openai的api (Issue #1)




这段代码里调用的是Azure上的openai的api，这样比直接调用麻烦很多，如何直接调用呢

—
Reply to this email directly, view it on GitHub or unsubscribe.
You are receiving this email because you are subscribed to this thread.

Triage notifications on the go with GitHub Mobile for iOS or Android.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

**Comment by linjungz** [comment]
https://mp.weixin.qq.com/s/xm9jMpBcWZwWTKBRDCbI7g


你可以参考这里 有讲用langchain的好处在哪



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenhualiu ***@***.***&gt;
发送时间: 2023年7月4日 21:40
收件人: linjungz/chatgpt-comment-analyzer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [linjungz/chatgpt-comment-analyzer] 如何直接调用openai的api (Issue #1)




这段代码里调用的是Azure上的openai的api，这样比直接调用麻烦很多，如何直接调用呢

—
Reply to this email directly, view it on GitHub or unsubscribe.
You are receiving this email because you are subscribed to this thread.

Triage notifications on the go with GitHub Mobile for iOS or Android.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
